#!/bin/bash

# This script runs the patch testing process by passing patcher_main.sh through an expect script to deal with the password prompt

# expext/autoexpect SOURCE: https://web.archive.org/web/20160404120518/http://www.linuxjournal.com/article/3065?page=0,0

while read p; do
	# this .exp file is generated by autoexpect, it is slighlty modified
	./expect_pswd.exp 'patcher_main.sh' $p
done < patches.txt
