#!/bin/bash

# This script runs the patch testing process by passing patcher_main.sh through an expect script to deal with the password prompt

# expext/autoexpect SOURCE: https://web.archive.org/web/20160404120518/http://www.linuxjournal.com/article/3065?page=0,0
patch_num=1
while read patch; do
	# this .exp file is generated by autoexpect, it is slighlty modified
	./expect_pswd.exp 'patcher_main.sh' $patch $patch_num
	patch_num=$(( $patch_num + 1 ))

	dirname=$(echo "${patch}" | awk '{print substr ($0, 0, 4)}')
	mkdir by_ten_trials/$dirname
	mv temp_location/* by_ten_trials/$dirname
done < patches.txt

# plot the graphs for the averages and variances
gnuplot -c run.gnuplot average.csv avg.png "Average Time Per Patch With n=10" "Patches" "Time"
gnuplot -c run.gnuplot variance.csv var.png "Variance Per Patch With n=10" "Patches" "Variance"
